numero1=float(input("digite um numero:"))
numero2=float(input("digite um numero:"))
soma=(numero1+numero2)
mutipli=(numero1*numero2)
divi=(numero1/numero2)
subtra=(numero1-numero2)
print("Soma:",soma)
print("Mutiplicação:",mutipli)
print("Divisão:",divi)
print("Subtração:",subtra)